- name: Setup web server
  hosts: all
  tasks:
    - name: Install httpd
      package:
        name: httpd
        state: present

    - name: Autostart httpd
      service:
        name: httpd
        enabled: true